#!/usr/bin/env bash
# Publish one of the two pages to a Cloudflare Worker, and optionally to an origin host as well.
#
#   ./deploy/publish.sh airdrop
#   ./deploy/publish.sh check
#
# Configuration comes from the environment, or from deploy/local.env if that file exists (it is gitignored;
# copy deploy/local.env.example to start one). Nothing here contains a credential.
#
#   CF_ACCOUNT_ID        required. Cloudflare account the worker belongs to.
#   CF_API_TOKEN         required, unless CF_API_TOKEN_FILE points at a file holding it.
#   CF_API_TOKEN_FILE    a file containing the token, so it never sits in a shell history or an env dump.
#   WORKER_AIRDROP       worker script name for the airdrop page   (default: rh-airdrop)
#   WORKER_CHECK         worker script name for the check page     (default: rh-check)
#   URL_AIRDROP          the URL to verify after publishing, if the worker has a custom domain
#   URL_CHECK            likewise for the check page
#   ORIGIN_PUBLISH_CMD   optional. Run for an origin copy as: $ORIGIN_PUBLISH_CMD <built file> <target name>
#   WC_BUNDLE_URL        optional. Where the worker fetches the WalletConnect bundle for /wc.js.
#
# Attaching a hostname to a worker is a one-off, separate from publishing:
#   PUT https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/domains
#   {"environment":"production","hostname":"<host>","service":"<worker name>","zone_id":"<zone>"}
# It fails with code 100117 if a DNS record for that hostname already exists; delete the record first.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -f "$ROOT/deploy/local.env" ] && . "$ROOT/deploy/local.env"

TARGET="${1:-}"
case "$TARGET" in
  airdrop) SRC="$ROOT/web/index.html"; WORKER="${WORKER_AIRDROP:-rh-airdrop}"; VERIFY="${URL_AIRDROP:-}"; ORIGIN_NAME="${ORIGIN_NAME_AIRDROP:-rhairdrop}" ;;
  check)   SRC="$ROOT/web/check.html"; WORKER="${WORKER_CHECK:-rh-check}";    VERIFY="${URL_CHECK:-}";   ORIGIN_NAME="${ORIGIN_NAME_CHECK:-rhcheck}" ;;
  *) echo "usage: $0 airdrop|check" >&2; exit 2 ;;
esac

: "${CF_ACCOUNT_ID:?set CF_ACCOUNT_ID (see the header of this script)}"
if [ -z "${CF_API_TOKEN:-}" ]; then
  : "${CF_API_TOKEN_FILE:?set CF_API_TOKEN or CF_API_TOKEN_FILE}"
  CF_API_TOKEN="$(tr -d '\n' < "$CF_API_TOKEN_FILE")"
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# The page is inlined into the worker as a string constant, so the worker serves it from the edge with no
# origin request at all. Everything the page needs beyond that is fetched by the browser.
python3 - "$SRC" "$WORK/worker.js" "$TARGET" "${WC_BUNDLE_URL:-}" <<'PY'
import json, sys
src, out, target, wc_bundle = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
html = open(src, encoding="utf-8").read()

wc_route = """
  // The WalletConnect bundle is served from this same origin, so importing it needs no CORS and the page
  // never takes signing code from a third party.
  if (url.pathname === '/wc.js') {
    if (!WC_BUNDLE) return new Response('connector not configured', { status: 404 });
    const upstream = await fetch(WC_BUNDLE, { cf: { cacheEverything: true, cacheTtl: 86400 } });
    if (!upstream.ok) return new Response('connector unavailable', { status: 502 });
    return new Response(upstream.body, { headers: { 'content-type': 'application/javascript; charset=utf-8', 'cache-control': 'public, max-age=86400', 'x-content-type-options': 'nosniff' } });
  }
""" if target == "airdrop" else ""

x_route = """
  // The mainnet explorer sends no Access-Control-Allow-Origin, so a browser cannot read it from this page.
  // A worker can: it is a server. Read-only, one host per chain id, and nothing but the API path is passed on.
  const x = url.pathname.match(/^\\/x\\/(4663|46630)(\\/[A-Za-z0-9_\\-\\/.]{1,200})$/);
  if (x) {
    const base = EXPLORERS[x[1]];
    if (!base || x[2].includes('..')) return new Response('bad path', { status: 400 });
    // The mainnet explorer answers browsers and challenges everything else, so ask the way a browser does.
    // One reader's lookup at a time, cached at the edge for a minute so it stays that way.
    const upstream = await fetch(base + '/api/v2' + x[2] + url.search, {
      headers: { accept: 'application/json', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' },
      cf: { cacheEverything: true, cacheTtl: 60 },
    });
    return new Response(upstream.body, { status: upstream.status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=60', 'x-content-type-options': 'nosniff' } });
  }
""" if target == "check" else ""

open(out, "w", encoding="utf-8").write(
"""// Serves the %s page from Cloudflare's edge. Generated by deploy/publish.sh; do not edit by hand.
const HTML = %s;
const WC_BUNDLE = %s;
const EXPLORERS = { '4663': 'https://robinhoodchain.blockscout.com', '46630': 'https://explorer.testnet.chain.robinhood.com' };
export default { async fetch(request) {
  const url = new URL(request.url);
%s%s  if (url.pathname !== '/' && url.pathname !== '/index.html') return new Response('Not found', { status: 404, headers: { 'content-type': 'text/plain; charset=utf-8' } });
  return new Response(HTML, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=300', 'x-content-type-options': 'nosniff', 'referrer-policy': 'strict-origin-when-cross-origin', 'content-security-policy': "frame-ancestors 'none'" } });
} };
""" % (target, json.dumps(html), json.dumps(wc_bundle or None), wc_route, x_route))
PY

node --check "$WORK/worker.js" 2>/dev/null || { echo "the generated worker does not parse" >&2; exit 1; }

curl -s -m 90 -X PUT -H "Authorization: Bearer $CF_API_TOKEN" \
  -F 'metadata={"main_module":"worker.js","compatibility_date":"2026-09-01"};type=application/json' \
  -F "worker.js=@$WORK/worker.js;type=application/javascript+module" \
  "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/$WORKER" \
  | python3 -c "import sys,json;d=json.load(sys.stdin);ok=d.get('success');print('worker',('published' if ok else 'FAILED'),[(e.get('code'),e.get('message')) for e in d.get('errors',[])][:2]);sys.exit(0 if ok else 1)"

if [ -n "${ORIGIN_PUBLISH_CMD:-}" ]; then
  $ORIGIN_PUBLISH_CMD "$SRC" "$ORIGIN_NAME"
fi

# A 200 proves something answered, not that it answered with the file that was just reviewed. Compare the
# bytes: a custom domain still pointing at an older worker returns 200 all day.
verify_body () {
  local url="$1" want="$2" label="$3" got=""
  local want_sum; want_sum="$(sha256sum "$want" | cut -d' ' -f1)"
  for _ in 1 2 3 4 5 6; do
    got="$(curl -s -m 25 "$url" | sha256sum | cut -d' ' -f1 || true)"
    [ "$got" = "$want_sum" ] && break
    sleep 5
  done
  if [ "$got" = "$want_sum" ]; then
    echo "$label $url matches $want  ($want_sum)"
  else
    echo "$label $url DOES NOT match $want" >&2
    echo "  served $got" >&2
    echo "  local  $want_sum" >&2
    return 1
  fi
}

FAILED=0
[ -n "$VERIFY" ] && { verify_body "$VERIFY" "$SRC" "page:" || FAILED=1; }
if [ "$TARGET" = "airdrop" ] && [ -n "$VERIFY" ] && [ -f "$ROOT/web/wc.js" ]; then
  verify_body "${VERIFY%/}/wc.js" "$ROOT/web/wc.js" "connector:" || FAILED=1
fi
exit $FAILED
